DROP TABLE IF EXISTS PANORMIC_HOTEL_RESERVATION;

CREATE TABLE PANORMIC_HOTEL_RESERVATION (
 RESERVATION_ID INT PRIMARY KEY NOT NULL,
 FIRST_NAME VARCHAR(100) NOT NULL,
 LAST_NAME VARCHAR(100) NOT NULL,
 STATUS VARCHAR(20) NOT NULL,
 EMAIL_ADDRESS VARCHAR(100),
 MOBILE_NO VARCHAR(15),
 CHECK_IN_DATE DATE NOT NULL,
 CHECK_OUT_DATE DATE,
 NO_OF_PERSONS INT NOT NULL,
 NO_OF_ADULTS INT,
 NO_OF_CHILDRENS INT,
 ROOM_NO INT NOT NULL); 
 
